# - name: Disable nginx default version
#   ansible.builtin.shell: dnf module disable nginx -y
#
# - name: Enable nginx version 1.24
#   ansible.builtin.shell: dnf module disable nginx -y
#
# - name: Install nginx
#   ansible.builtin.dnf:
#     name: nginx
#     state: installed
#
# - name: Copy nginx config
#   ansible.builtin.template:
#     src: nginx.conf
#     dest: /etc/nginx/nginx.conf
#
# - name: Remove nginx default content
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/
#     state: absent
#
# - name: Create nginx http directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/
#     state: directory
#
# - name: Download nginx content
#   ansible.builtin.unarchive:
#     src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#     dest: /usr/share/nginx/html/
#     remote_src: yes
#
# - name: Start nginx
#   ansible.builtin.systemd_service:
#     name: nginx
#     state: restarted
#     enabled: yes
#
#

- name: Load Docker
  ansible.builtin.import_role:
    name: common
    tasks_from: docker

- name: Launch Docker Container
  community.docker.docker_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    ports:
      - "80:80"
    env:
      CATALOGUE_HOST: catalogue-dev.rdevopsb85.online
      CATALOGUE_PORT: "8080"
      USER_HOST: user-dev.rdevopsb85.online
      USER_PORT: "8080"
      CART_HOST: cart-dev.rdevopsb85.online
      CART_PORT: "8080"
      SHIPPING_HOST: shipping-dev.rdevopsb85.online
      SHIPPING_PORT: "8080"
      PAYMENT_HOST: payment-dev.rdevopsb85.online
      PAYMENT_PORT: "8080"