- name: Copy RabbitMQ repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitMQ server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ server
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Create RabbitMQ User
  ansible.builtin.shell: rabbitmqctl add_user {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/rabbitmq:APP_USER token={{ token }} url=http://vault-internal.rdevopsb85.online:8200') }} {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/rabbitmq:APP_PASSWORD token={{ token }} url=http://vault-internal.rdevopsb85.online:8200') }} ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"





