- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ role_name }}

- name: Copy Elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install ELK
  ansible.builtin.dnf:
    name:
      - elasticsearch
      - kibana
      - logstash
      - nginx
    state: installed

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start ELK
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx

- name: Copy logstash config
  ansible.builtin.template:
    src: beats.conf
    dest: /etc/logstash/conf.d/beats.conf

- name: Restart Logstash
  ansible.builtin.systemd_service:
    name: logstash
    state: restarted


